//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 01:52:24 PM PST 
//


package ca.bc.gov.tno.jorel2.jaxb.dailyhive;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.bc.gov.tno.jorel2.jaxb.dailyhive package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.bc.gov.tno.jorel2.jaxb.dailyhive
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DailyHiveRss }
     * 
     * @return New DailiHiveRss object
     */
    public DailyHiveRss createRss() {
        return new DailyHiveRss();
    }

    /**
     * Create an instance of {@link DailyHiveRss.Channel }
     * 
     * @return new DailyHiveRss.Channel object
     */
    public DailyHiveRss.Channel createRssChannel() {
        return new DailyHiveRss.Channel();
    }

    /**
     * Create an instance of {@link DailyHiveRss.Channel.Item }
     * 
     * @return New DailyHiveRss.Channel.Item object
     */
    public DailyHiveRss.Channel.Item createRssChannelItem() {
        return new DailyHiveRss.Channel.Item();
    }

    /**
     * Create an instance of {@link DailyHiveRss.Channel.Atomlink }
     * 
     * @return New DailyHiveRss.Channel.Atomlink object
     */
    public DailyHiveRss.Channel.Atomlink createRssChannelAtomlink() {
        return new DailyHiveRss.Channel.Atomlink();
    }

    /**
     * Create an instance of {@link DailyHiveRss.Channel.Item.Guid }
     * 
     * @return New DailyHiveRss.Channel.Item.Guid object
     */
    public DailyHiveRss.Channel.Item.Guid createRssChannelItemGuid() {
        return new DailyHiveRss.Channel.Item.Guid();
    }

    /**
     * Create an instance of {@link DailyHiveRss.Channel.Item.Enclosure }
     * 
     * @return New DailyHiveRss.Channel.Item.Enclosure object
     */
    public DailyHiveRss.Channel.Item.Enclosure createRssChannelItemEnclosure() {
        return new DailyHiveRss.Channel.Item.Enclosure();
    }

}
