//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 03:12:28 PM PDT 
//


package ca.bc.gov.tno.jorel2.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="head"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="pubdata"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="date.publication" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="edition.name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="position.section" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="position.sequence" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="body.head"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="hedline"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="hl1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="hl2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="byline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="dateline"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="body.content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "nitf")
public class Nitf {

    @XmlElement(required = true)
    protected Nitf.Head head;
    @XmlElement(required = true)
    protected Nitf.Body body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Nitf.Head }
     *     
     */
    public Nitf.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nitf.Head }
     *     
     */
    public void setHead(Nitf.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link Nitf.Body }
     *     
     */
    public Nitf.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nitf.Body }
     *     
     */
    public void setBody(Nitf.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="body.head"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="hedline"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="hl1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="hl2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="byline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="dateline"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="body.content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bodyHead",
        "bodyContent"
    })
    public static class Body {

        @XmlElement(name = "body.head", required = true)
        protected Nitf.Body.BodyHead bodyHead;
        @XmlElement(name = "body.content", required = true)
        protected String bodyContent;

        /**
         * Gets the value of the bodyHead property.
         * 
         * @return
         *     possible object is
         *     {@link Nitf.Body.BodyHead }
         *     
         */
        public Nitf.Body.BodyHead getBodyHead() {
            return bodyHead;
        }

        /**
         * Sets the value of the bodyHead property.
         * 
         * @param value
         *     allowed object is
         *     {@link Nitf.Body.BodyHead }
         *     
         */
        public void setBodyHead(Nitf.Body.BodyHead value) {
            this.bodyHead = value;
        }

        /**
         * Gets the value of the bodyContent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBodyContent() {
            return bodyContent;
        }

        /**
         * Sets the value of the bodyContent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBodyContent(String value) {
            this.bodyContent = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="hedline"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="hl1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="hl2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="byline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="dateline"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hedline",
            "byline",
            "credit",
            "dateline"
        })
        public static class BodyHead {

            @XmlElement(required = true)
            protected Nitf.Body.BodyHead.Hedline hedline;
            @XmlElement(required = true)
            protected String byline;
            @XmlElement(required = true)
            protected String credit;
            @XmlElement(required = true)
            protected Nitf.Body.BodyHead.Dateline dateline;

            /**
             * Gets the value of the hedline property.
             * 
             * @return
             *     possible object is
             *     {@link Nitf.Body.BodyHead.Hedline }
             *     
             */
            public Nitf.Body.BodyHead.Hedline getHedline() {
                return hedline;
            }

            /**
             * Sets the value of the hedline property.
             * 
             * @param value
             *     allowed object is
             *     {@link Nitf.Body.BodyHead.Hedline }
             *     
             */
            public void setHedline(Nitf.Body.BodyHead.Hedline value) {
                this.hedline = value;
            }

            /**
             * Gets the value of the byline property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getByline() {
                return byline;
            }

            /**
             * Sets the value of the byline property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setByline(String value) {
                this.byline = value;
            }

            /**
             * Gets the value of the credit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCredit() {
                return credit;
            }

            /**
             * Sets the value of the credit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCredit(String value) {
                this.credit = value;
            }

            /**
             * Gets the value of the dateline property.
             * 
             * @return
             *     possible object is
             *     {@link Nitf.Body.BodyHead.Dateline }
             *     
             */
            public Nitf.Body.BodyHead.Dateline getDateline() {
                return dateline;
            }

            /**
             * Sets the value of the dateline property.
             * 
             * @param value
             *     allowed object is
             *     {@link Nitf.Body.BodyHead.Dateline }
             *     
             */
            public void setDateline(Nitf.Body.BodyHead.Dateline value) {
                this.dateline = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "location"
            })
            public static class Dateline {

                @XmlElement(required = true)
                protected String location;

                /**
                 * Gets the value of the location property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLocation() {
                    return location;
                }

                /**
                 * Sets the value of the location property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLocation(String value) {
                    this.location = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="hl1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="hl2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "hl1",
                "hl2"
            })
            public static class Hedline {

                @XmlElement(required = true)
                protected String hl1;
                @XmlElement(required = true)
                protected String hl2;

                /**
                 * Gets the value of the hl1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHl1() {
                    return hl1;
                }

                /**
                 * Sets the value of the hl1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHl1(String value) {
                    this.hl1 = value;
                }

                /**
                 * Gets the value of the hl2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHl2() {
                    return hl2;
                }

                /**
                 * Sets the value of the hl2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHl2(String value) {
                    this.hl2 = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="pubdata"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="date.publication" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="edition.name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="position.section" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="position.sequence" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pubdata",
        "title"
    })
    public static class Head {

        @XmlElement(required = true)
        protected Nitf.Head.Pubdata pubdata;
        @XmlElement(required = true)
        protected String title;

        /**
         * Gets the value of the pubdata property.
         * 
         * @return
         *     possible object is
         *     {@link Nitf.Head.Pubdata }
         *     
         */
        public Nitf.Head.Pubdata getPubdata() {
            return pubdata;
        }

        /**
         * Sets the value of the pubdata property.
         * 
         * @param value
         *     allowed object is
         *     {@link Nitf.Head.Pubdata }
         *     
         */
        public void setPubdata(Nitf.Head.Pubdata value) {
            this.pubdata = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="date.publication" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="edition.name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="position.section" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="position.sequence" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Pubdata {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "date.publication")
            protected Integer datePublication;
            @XmlAttribute(name = "edition.name")
            protected String editionName;
            @XmlAttribute(name = "position.section")
            protected String positionSection;
            @XmlAttribute(name = "position.sequence")
            protected String positionSequence;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the datePublication property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDatePublication() {
                return datePublication;
            }

            /**
             * Sets the value of the datePublication property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDatePublication(Integer value) {
                this.datePublication = value;
            }

            /**
             * Gets the value of the editionName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEditionName() {
                return editionName;
            }

            /**
             * Sets the value of the editionName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEditionName(String value) {
                this.editionName = value;
            }

            /**
             * Gets the value of the positionSection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPositionSection() {
                return positionSection;
            }

            /**
             * Sets the value of the positionSection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPositionSection(String value) {
                this.positionSection = value;
            }

            /**
             * Gets the value of the positionSequence property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPositionSequence() {
                return positionSequence;
            }

            /**
             * Sets the value of the positionSequence property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPositionSequence(String value) {
                this.positionSequence = value;
            }

        }

    }

}
