//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.09 at 11:44:21 AM PST 
//


package ca.bc.gov.tno.jorel2.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

import ca.bc.gov.tno.jorel2.jaxb.Rss.Channel.Atomlink;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.bc.gov.tno.jorel2.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.bc.gov.tno.jorel2.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rss }
     * 
     * @return The top level Rss object.
     */
    public Rss createRss() {
        return new Rss();
    }

    /**
     * Create an instance of {@link Rss.Channel }
     * 
     * @return The channel.
     */
    public Rss.Channel createRssChannel() {
        return new Rss.Channel();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item }
     * 
     * @return The item.
     */
    public Rss.Channel.Item createRssChannelItem() {
        return new Rss.Channel.Item();
    }

    /**
     * Create an instance of {@link Rss.Channel.Atomlink }
     * 
     * @return The link.
     */
    public Atomlink createRssChannelAtomlink() {
        return new Atomlink();
    }

    /**
     * Create an instance of {@link Rss.Channel.Image }
     * 
     * @return The image.
     */
    public Rss.Channel.Image createRssChannelImage() {
        return new Rss.Channel.Image();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Guid }
     * 
     * @return The Guid.
     */
    public Rss.Channel.Item.Guid createRssChannelItemGuid() {
        return new Rss.Channel.Item.Guid();
    }

}
