package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * EventClips generated by hbm2java
 */
@Entity
@Table(name = "EVENT_CLIPS", schema = "TNO")
public class EventClipsDao implements java.io.Serializable {

	private BigDecimal rsn;
	private BigDecimal eventRsn;
	private String name;
	private String startTime;
	private String stopTime;
	private String frequency;
	private String lastRun;

	public EventClipsDao() {
	}

	public EventClipsDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public EventClipsDao(BigDecimal rsn, BigDecimal eventRsn, String name, String startTime, String stopTime,
			String frequency, String lastRun) {
		this.rsn = rsn;
		this.eventRsn = eventRsn;
		this.name = name;
		this.startTime = startTime;
		this.stopTime = stopTime;
		this.frequency = frequency;
		this.lastRun = lastRun;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "EVENT_RSN", precision = 38, scale = 0)
	public BigDecimal getEventRsn() {
		return this.eventRsn;
	}

	public void setEventRsn(BigDecimal eventRsn) {
		this.eventRsn = eventRsn;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "START_TIME", length = 10)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "STOP_TIME", length = 10)
	public String getStopTime() {
		return this.stopTime;
	}

	public void setStopTime(String stopTime) {
		this.stopTime = stopTime;
	}

	@Column(name = "FREQUENCY", length = 10)
	public String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	@Column(name = "LAST_RUN", length = 20)
	public String getLastRun() {
		return this.lastRun;
	}

	public void setLastRun(String lastRun) {
		this.lastRun = lastRun;
	}
	
	/**
	 * Retrieves all EventClipsDao objects corresponding to the eventRsn stored in the eventRsn parameter.
	 *  
	 * @param rsn The key of the records to read.
	 * @param session The current Hibernate persistence context
	 * @return The EventsDao object corresponding to the key stored in the rsn parameter.
	 */
	public static List<EventClipsDao> getClipsByEventRsn(BigDecimal eventRsn, Session session) {
		
		Query<EventClipsDao> query = session.createQuery("from EventClipsDao where eventRsn = :eventRsn", EventClipsDao.class);
		query.setParameter("eventRsn", eventRsn);
		
        List<EventClipsDao> results = query.getResultList();
        
		return results;
	}
}
