package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventActivityLog generated by hbm2java
 */
@Entity
@Table(name = "EVENT_ACTIVITY_LOG", schema = "TNO")
public class EventActivityLogDao implements java.io.Serializable {

	private BigDecimal rsn;
	private String process;
	private Date entryDate;
	private String notes;

	public EventActivityLogDao() {
	}

	public EventActivityLogDao(BigDecimal rsn, String process) {
		this.rsn = rsn;
		this.process = process;
	}

	public EventActivityLogDao(BigDecimal rsn, String process, Date entryDate, String notes) {
		this.rsn = rsn;
		this.process = process;
		this.entryDate = entryDate;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "next_rsn")
	@SequenceGenerator(name = "next_rsn", sequenceName = "NEXT_RSN", allocationSize=1)
	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "PROCESS", nullable = false, length = 30)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENTRY_DATE", length = 7)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "NOTES", length = 2000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
