package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * FilesImported generated by hbm2java
 */
@Entity
@Table(name = "FILES_IMPORTED", schema = "TNO")
public class FilesImportedDao implements java.io.Serializable {

	private BigDecimal rsn;
	private Date dateImported;
	private String fileName;

	public FilesImportedDao() {
	}

	public FilesImportedDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public FilesImportedDao(BigDecimal rsn, Date dateImported, String fileName) {
		this.rsn = rsn;
		this.dateImported = dateImported;
		this.fileName = fileName;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_IMPORTED", length = 7)
	public Date getDateImported() {
		return this.dateImported;
	}

	public void setDateImported(Date dateImported) {
		this.dateImported = dateImported;
	}

	@Column(name = "FILE_NAME", length = 200)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	
	/**
	 * Get the FilesImportedDao record(s) matching the fileName.
	 *
	 * @param fileName The fileName to match.
	 * @param session The current Hibernate persistence context
	 * @return The record(s) matching fileName
	 */
	public static List<FilesImportedDao> getFilesImportedByFileName(String fileName, Session session) {
		
		String sqlStmt = "from FilesImportedDao where fileName=:fileName";
		
		Query<FilesImportedDao> query = session.createQuery(sqlStmt, FilesImportedDao.class);
		query.setParameter("fileName", fileName);
        List<FilesImportedDao> results = query.getResultList();
        
        return results;
	}

}
