package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * FileQueue generated by hbm2java
 */
@Entity
@Table(name = "FILE_QUEUE", schema = "TNO")
public class FileQueueDao implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal rsn;
	private String filename;
	private String fullfilepath;
	private String downloadedBy;
	private Boolean downloaded;
	private Boolean created;
	private Boolean uploaded;
	private Date dateInserted;
	private Date dateFinished;
	private BigDecimal count;
	private String target;

	public FileQueueDao() {
	}

	public FileQueueDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public FileQueueDao(BigDecimal rsn, String filename, String fullfilepath, String downloadedBy, Boolean downloaded,
			Boolean created, Boolean uploaded, Date dateInserted, Date dateFinished, BigDecimal count, String target) {
		this.rsn = rsn;
		this.filename = filename;
		this.fullfilepath = fullfilepath;
		this.downloadedBy = downloadedBy;
		this.downloaded = downloaded;
		this.created = created;
		this.uploaded = uploaded;
		this.dateInserted = dateInserted;
		this.dateFinished = dateFinished;
		this.count = count;
		this.target = target;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "FILENAME", length = 100)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "FULLFILEPATH", length = 1000)
	public String getFullfilepath() {
		return this.fullfilepath;
	}

	public void setFullfilepath(String fullfilepath) {
		this.fullfilepath = fullfilepath;
	}

	@Column(name = "DOWNLOADED_BY", length = 50)
	public String getDownloadedBy() {
		return this.downloadedBy;
	}

	public void setDownloadedBy(String downloadedBy) {
		this.downloadedBy = downloadedBy;
	}

	@Column(name = "DOWNLOADED", precision = 1, scale = 0)
	public Boolean getDownloaded() {
		return this.downloaded;
	}

	public void setDownloaded(Boolean downloaded) {
		this.downloaded = downloaded;
	}

	@Column(name = "CREATED", precision = 1, scale = 0)
	public Boolean getCreated() {
		return this.created;
	}

	public void setCreated(Boolean created) {
		this.created = created;
	}

	@Column(name = "UPLOADED", precision = 1, scale = 0)
	public Boolean getUploaded() {
		return this.uploaded;
	}

	public void setUploaded(Boolean uploaded) {
		this.uploaded = uploaded;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_INSERTED", length = 7)
	public Date getDateInserted() {
		return this.dateInserted;
	}

	public void setDateInserted(Date dateInserted) {
		this.dateInserted = dateInserted;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FINISHED", length = 7)
	public Date getDateFinished() {
		return this.dateFinished;
	}

	public void setDateFinished(Date dateFinished) {
		this.dateFinished = dateFinished;
	}

	@Column(name = "COUNT", precision = 38, scale = 0)
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	@Column(name = "TARGET", length = 10)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}
	
	public String toString() {
		return "Filename = " + filename;
	}
	
	/**
	 * Get the number of NEWS_ITEMS records for this publisher.
	 *
	 * @param target The category of file whose duration should be calculated
	 * @param session The current Hibernate persistence context
	 * @return The number of NEWS_ITMES records generated by this publisher
	 */
	public static List<FileQueueDao> getQueuedFilesByTarget(String target, Session session) {
		
		String sqlStmt = "from FileQueueDao where target=:target";
		
		Query<FileQueueDao> query = session.createQuery(sqlStmt, FileQueueDao.class);
		query.setParameter("target", target);
        List<FileQueueDao> results = query.getResultList();
        
        return results;
	}
}
