package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * ImportDefinitions generated by hbm2java
 */
@Entity
@Table(name = "IMPORT_DEFINITIONS", schema = "TNO")
public class ImportDefinitionsDao implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal rsn;
	private String name;
	private String type;
	private String fieldDelimiter;
	private String recordDelimiter;
	private Clob positionList;
	private Boolean autoPublishWeekend;
	private Boolean autoFpA01;

	public ImportDefinitionsDao() {
	}

	public ImportDefinitionsDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public ImportDefinitionsDao(BigDecimal rsn, String name, String type, String fieldDelimiter, String recordDelimiter,
			Clob positionList, Boolean autoPublishWeekend, Boolean autoFpA01) {
		this.rsn = rsn;
		this.name = name;
		this.type = type;
		this.fieldDelimiter = fieldDelimiter;
		this.recordDelimiter = recordDelimiter;
		this.positionList = positionList;
		this.autoPublishWeekend = autoPublishWeekend;
		this.autoFpA01 = autoFpA01;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "NAME", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "FIELD_DELIMITER", length = 10)
	public String getFieldDelimiter() {
		return this.fieldDelimiter;
	}

	public void setFieldDelimiter(String fieldDelimiter) {
		this.fieldDelimiter = fieldDelimiter;
	}

	@Column(name = "RECORD_DELIMITER", length = 10)
	public String getRecordDelimiter() {
		return this.recordDelimiter;
	}

	public void setRecordDelimiter(String recordDelimiter) {
		this.recordDelimiter = recordDelimiter;
	}

	@Column(name = "POSITION_LIST")
	public Clob getPositionList() {
		return this.positionList;
	}

	public void setPositionList(Clob positionList) {
		this.positionList = positionList;
	}

	@Column(name = "AUTO_PUBLISH_WEEKEND", precision = 1, scale = 0)
	public Boolean getAutoPublishWeekend() {
		return this.autoPublishWeekend;
	}

	public void setAutoPublishWeekend(Boolean autoPublishWeekend) {
		this.autoPublishWeekend = autoPublishWeekend;
	}

	@Column(name = "AUTO_FP_A01", precision = 1, scale = 0)
	public Boolean getAutoFpA01() {
		return this.autoFpA01;
	}

	public void setAutoFpA01(Boolean autoFpA01) {
		this.autoFpA01 = autoFpA01;
	}
	
	/**
	 * Retrieves the ImportDefinitionsDao object corresponding to the name parameter.
	 *  
	 * @param name The match field of the record to read.
	 * @param session The current Hibernate persistence context
	 * @return The ImportDefinitionsDao object matching the name parameter.
	 */
	public static List<ImportDefinitionsDao> getDefinitionByName(String name, Session session) {
		
		Query<ImportDefinitionsDao> query = session.createQuery("from ImportDefinitionsDao where name=:name", ImportDefinitionsDao.class);
		query.setParameter("name", name);
        List<ImportDefinitionsDao> results = query.getResultList();
        
		return results;
	}
		

}
