package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Influencers generated by hbm2java
 */
@Entity
@Table(name = "INFLUENCERS", schema = "TNO")
public class InfluencersDao implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal rsn;
	private String name;
	private BigDecimal tnoWeight;

	public InfluencersDao() {
	}

	public InfluencersDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public InfluencersDao(BigDecimal rsn, String name, BigDecimal tnoWeight) {
		this.rsn = rsn;
		this.name = name;
		this.tnoWeight = tnoWeight;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TNO_WEIGHT", precision = 10, scale = 3)
	public BigDecimal getTnoWeight() {
		return this.tnoWeight;
	}

	public void setTnoWeight(BigDecimal tnoWeight) {
		this.tnoWeight = tnoWeight;
	}
}
