package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * Issues generated by hbm2java
 */
@Entity
@Table(name = "ISSUES", schema = "TNO")
public class IssuesDao implements Jorel2ArticleFilter, java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal rsn;
	private String issue;
	private String words;
	private String wordsCaseSensitive;
	private BigDecimal minOccurance;
	private Boolean publicflag;
	private Boolean enabled;

	public IssuesDao() {
	}

	public IssuesDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public IssuesDao(BigDecimal rsn, String issue, String words, String wordsCaseSensitive, BigDecimal minOccurance,
			Boolean publicflag, Boolean enabled) {
		this.rsn = rsn;
		this.issue = issue;
		this.words = words;
		this.wordsCaseSensitive = wordsCaseSensitive;
		this.minOccurance = minOccurance;
		this.publicflag = publicflag;
		this.enabled = enabled;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "ISSUE", length = 100)
	public String getIssue() {
		return this.issue;
	}

	public void setIssue(String issue) {
		this.issue = issue;
	}

	@Column(name = "WORDS", length = 2000)
	public String getWords() {
		return this.words;
	}

	public void setWords(String words) {
		this.words = words;
	}

	@Column(name = "WORDS_CASE_SENSITIVE", length = 2000)
	public String getWordsCaseSensitive() {
		return this.wordsCaseSensitive;
	}

	public void setWordsCaseSensitive(String wordsCaseSensitive) {
		this.wordsCaseSensitive = wordsCaseSensitive;
	}

	@Column(name = "MIN_OCCURANCE", precision = 38, scale = 0)
	public BigDecimal getMinOccurance() {
		return this.minOccurance;
	}

	public void setMinOccurance(BigDecimal minOccurance) {
		this.minOccurance = minOccurance;
	}

	@Column(name = "PUBLICFLAG", precision = 1, scale = 0)
	public Boolean getPublicflag() {
		return this.publicflag;
	}

	public void setPublicflag(Boolean publicflag) {
		this.publicflag = publicflag;
	}

	@Column(name = "ENABLED", precision = 1, scale = 0)
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}
	
	/**
	 * Returns all records in the ISSUES table that are enabled (enabled=1).
	 * 
	 * @param session - The currently active Hibernate DB session
	 * @return List of EventsDao objects that match the Events_FindEventsForProcessing named query.
	 */
	public static List<Jorel2ArticleFilter> getEnabledRecordList(Session session) {

		Query<Jorel2ArticleFilter> query = session.createQuery("from IssuesDao where enabled=1", Jorel2ArticleFilter.class);
        List<Jorel2ArticleFilter> results = query.getResultList();
        
        return results;
	}
}
