package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * NewsItemIssuesId generated by hbm2java
 */
@Entity
@Table(name = "NEWS_ITEM_ISSUES")
public class NewsItemIssuesDao implements ArticleFlagger, java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private BigDecimal itemRsn;
	private BigDecimal issueRsn;
	private Date entryDate;

	public NewsItemIssuesDao() {
	}

	public NewsItemIssuesDao(BigDecimal itemRsn, BigDecimal issueRsn, Date entryDate) {
		this.itemRsn = itemRsn;
		this.issueRsn = issueRsn;
		this.entryDate = entryDate;
	}

	@Id
	@Column(name = "ITEM_RSN", precision = 38, scale = 0)
	public BigDecimal getItemRsn() {
		return this.itemRsn;
	}

	public void setItemRsn(BigDecimal itemRsn) {
		this.itemRsn = itemRsn;
	}

	@Column(name = "ISSUE_RSN", precision = 38, scale = 0)
	public BigDecimal getIssueRsn() {
		return this.issueRsn;
	}

	public void setIssueRsn(BigDecimal issueRsn) {
		this.issueRsn = issueRsn;
	}

	@Column(name = "ENTRY_DATE", length = 7)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NewsItemIssuesDao))
			return false;
		NewsItemIssuesDao castOther = (NewsItemIssuesDao) other;

		return ((this.getItemRsn() == castOther.getItemRsn()) || (this.getItemRsn() != null
				&& castOther.getItemRsn() != null && this.getItemRsn().equals(castOther.getItemRsn())))
				&& ((this.getIssueRsn() == castOther.getIssueRsn()) || (this.getIssueRsn() != null
						&& castOther.getIssueRsn() != null && this.getIssueRsn().equals(castOther.getIssueRsn())))
				&& ((this.getEntryDate() == castOther.getEntryDate()) || (this.getEntryDate() != null
						&& castOther.getEntryDate() != null && this.getEntryDate().equals(castOther.getEntryDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getItemRsn() == null ? 0 : this.getItemRsn().hashCode());
		result = 37 * result + (getIssueRsn() == null ? 0 : this.getIssueRsn().hashCode());
		result = 37 * result + (getEntryDate() == null ? 0 : this.getEntryDate().hashCode());
		return result;
	}
	
	/**
	 * Returns all Jorel entries in the NEWS_ITEMS_ISSUES table.
	 * 
	 * @param session - The currently active Hibernate DB session
	 * @return List of NewsItemIssues objects that match the Events_FindEventsForProcessing named query.
	 */
	public static List<NewsItemIssuesDao> getNewsItemIssues(Session session) {

		Query<NewsItemIssuesDao> query = session.createQuery("from NewsItemIssuesDao");
        List<NewsItemIssuesDao> results = query.getResultList();
        
        return results;
	}

}
