package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.Session;

import ca.bc.gov.tno.jorel2.controller.QuoteExtractor;

/**
 * NewsItemQuotes generated by hbm2java
 */
@Entity
@Table(name = "NEWS_ITEM_QUOTES", schema = "TNO")
public class NewsItemQuotesDao implements java.io.Serializable {

	private BigDecimal rsn;
	private BigDecimal itemRsn;
	private String name;
	private String alias;
	private String offsetLengths;
	private String modifiedQuoteText;
	private Boolean unknownAlias;

	public NewsItemQuotesDao() {
	}

	public NewsItemQuotesDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public NewsItemQuotesDao(BigDecimal rsn, BigDecimal itemRsn, String name, String alias, String offsetLengths,
			String modifiedQuoteText, Boolean unknownAlias) {
		this.rsn = rsn;
		this.itemRsn = itemRsn;
		this.name = name;
		this.alias = alias;
		this.offsetLengths = offsetLengths;
		this.modifiedQuoteText = modifiedQuoteText;
		this.unknownAlias = unknownAlias;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "next_rsn")
	@SequenceGenerator(name = "next_rsn", sequenceName = "NEXT_RSN", allocationSize=1)
	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "ITEM_RSN", precision = 38, scale = 0)
	public BigDecimal getItemRsn() {
		return this.itemRsn;
	}

	public void setItemRsn(BigDecimal itemRsn) {
		this.itemRsn = itemRsn;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ALIAS", length = 100)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "OFFSET_LENGTHS", length = 2000)
	public String getOffsetLengths() {
		return this.offsetLengths;
	}

	public void setOffsetLengths(String offsetLengths) {
		this.offsetLengths = offsetLengths;
	}

	@Column(name = "MODIFIED_QUOTE_TEXT", length = 4000)
	public String getModifiedQuoteText() {
		return this.modifiedQuoteText;
	}

	public void setModifiedQuoteText(String modifiedQuoteText) {
		this.modifiedQuoteText = modifiedQuoteText;
	}

	@Column(name = "UNKNOWN_ALIAS", precision = 1, scale = 0)
	public Boolean getUnknownAlias() {
		return this.unknownAlias;
	}

	public void setUnknownAlias(Boolean unknownAlias) {
		this.unknownAlias = unknownAlias;
	}

	/**
	 * Save all quotes extracted by <code>quoteExtractor</code> for the current news item. Transaction protection is performed at the 
	 * event level in insertNewsItems.
	 * 
	 * @param quoteExtractor The quote extractor object containing all quotes for the current news item.
	 * @param newsItem The news item being post-processed (needed to obtain foreign key [rsn] for new NewsItemQuotesDao record)
	 * @param session The current Hibernate persistence context.
	 */
	public static void saveQuotes(QuoteExtractor quoteExtractor, NewsItemsDao newsItem, Session session) {
		
	    while (quoteExtractor.next()) {
	    	NewsItemQuotesDao quote = new NewsItemQuotesDao(
	    		null,
	    		newsItem.getRsn(),
	        	quoteExtractor.getName(), 
	        	quoteExtractor.getAlias(), 
	        	quoteExtractor.getOffsetLengths(), 
	        	"",
	        	quoteExtractor.getUnknownAlias()
	        );
	    	
	    	session.persist(quote);        
	    }
	}
}
