package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * Preferences generated by hbm2java
 */
@Entity
@Table(name = "PREFERENCES", schema = "TNO")
public class PreferencesDao implements java.io.Serializable {

	private BigDecimal rsn;
	private BigDecimal servletListeners;
	private BigDecimal maxServletListeners;
	private BigDecimal userTimeout;
	private String defaultHomepage;
	private String defaultLoginpage;
	private String defaultPage404;
	private String lastArchiveRun;
	private String applicationTitle;
	private BigDecimal retainLogsFor;
	private BigDecimal minBinarySize;
	private String httpPutIps;
	private String clarkPublisher;
	private BigDecimal retainFullBroadcast;
	private String zeroResultsPage;
	private BigDecimal currentperiod;
	private BigDecimal briefingroomperiod;
	private BigDecimal truncCommentary;
	private Boolean wap;
	private Boolean alerts;
	private Boolean reports;
	private Boolean campaigns;
	private String topstoriesEmail;
	private Double commentaryTimeoutWeekday;
	private Double commentaryTimeoutWeekend;
	private BigDecimal quickLinkUrls;
	private Boolean rssAlerts;
	private BigDecimal retainImages;
	private BigDecimal retainSocialMedia;
	private BigDecimal itemsPerPage;
	private String decayforsocialmedia;
	private BigDecimal daysforbuzz;
	private Double buzz10;
	private String eodEmailList;
	private BigDecimal eodExpireAfter;
	private Boolean eodOn;
	private String smaEmailList;
	private String reloadParts;
	private String transcriptEmail;
	private String productEmail;
	private Boolean showEmoji;
	private Boolean azure;

	public PreferencesDao() {
	}

	public PreferencesDao(BigDecimal rsn, BigDecimal servletListeners, BigDecimal maxServletListeners,
			BigDecimal userTimeout, String defaultHomepage, String defaultLoginpage, String defaultPage404,
			String lastArchiveRun, String applicationTitle, BigDecimal retainLogsFor, String httpPutIps,
			String clarkPublisher) {
		this.rsn = rsn;
		this.servletListeners = servletListeners;
		this.maxServletListeners = maxServletListeners;
		this.userTimeout = userTimeout;
		this.defaultHomepage = defaultHomepage;
		this.defaultLoginpage = defaultLoginpage;
		this.defaultPage404 = defaultPage404;
		this.lastArchiveRun = lastArchiveRun;
		this.applicationTitle = applicationTitle;
		this.retainLogsFor = retainLogsFor;
		this.httpPutIps = httpPutIps;
		this.clarkPublisher = clarkPublisher;
	}

	public PreferencesDao(BigDecimal rsn, BigDecimal servletListeners, BigDecimal maxServletListeners,
			BigDecimal userTimeout, String defaultHomepage, String defaultLoginpage, String defaultPage404,
			String lastArchiveRun, String applicationTitle, BigDecimal retainLogsFor, BigDecimal minBinarySize,
			String httpPutIps, String clarkPublisher, BigDecimal retainFullBroadcast, String zeroResultsPage,
			BigDecimal currentperiod, BigDecimal briefingroomperiod, BigDecimal truncCommentary, Boolean wap,
			Boolean alerts, Boolean reports, Boolean campaigns, String topstoriesEmail, Double commentaryTimeoutWeekday,
			Double commentaryTimeoutWeekend, BigDecimal quickLinkUrls, Boolean rssAlerts, BigDecimal retainImages,
			BigDecimal retainSocialMedia, BigDecimal itemsPerPage, String decayforsocialmedia, BigDecimal daysforbuzz,
			Double buzz10, String eodEmailList, BigDecimal eodExpireAfter, Boolean eodOn, String smaEmailList,
			String reloadParts, String transcriptEmail, String productEmail, Boolean showEmoji, Boolean azure) {
		this.rsn = rsn;
		this.servletListeners = servletListeners;
		this.maxServletListeners = maxServletListeners;
		this.userTimeout = userTimeout;
		this.defaultHomepage = defaultHomepage;
		this.defaultLoginpage = defaultLoginpage;
		this.defaultPage404 = defaultPage404;
		this.lastArchiveRun = lastArchiveRun;
		this.applicationTitle = applicationTitle;
		this.retainLogsFor = retainLogsFor;
		this.minBinarySize = minBinarySize;
		this.httpPutIps = httpPutIps;
		this.clarkPublisher = clarkPublisher;
		this.retainFullBroadcast = retainFullBroadcast;
		this.zeroResultsPage = zeroResultsPage;
		this.currentperiod = currentperiod;
		this.briefingroomperiod = briefingroomperiod;
		this.truncCommentary = truncCommentary;
		this.wap = wap;
		this.alerts = alerts;
		this.reports = reports;
		this.campaigns = campaigns;
		this.topstoriesEmail = topstoriesEmail;
		this.commentaryTimeoutWeekday = commentaryTimeoutWeekday;
		this.commentaryTimeoutWeekend = commentaryTimeoutWeekend;
		this.quickLinkUrls = quickLinkUrls;
		this.rssAlerts = rssAlerts;
		this.retainImages = retainImages;
		this.retainSocialMedia = retainSocialMedia;
		this.itemsPerPage = itemsPerPage;
		this.decayforsocialmedia = decayforsocialmedia;
		this.daysforbuzz = daysforbuzz;
		this.buzz10 = buzz10;
		this.eodEmailList = eodEmailList;
		this.eodExpireAfter = eodExpireAfter;
		this.eodOn = eodOn;
		this.smaEmailList = smaEmailList;
		this.reloadParts = reloadParts;
		this.transcriptEmail = transcriptEmail;
		this.productEmail = productEmail;
		this.showEmoji = showEmoji;
		this.azure = azure;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "SERVLET_LISTENERS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getServletListeners() {
		return this.servletListeners;
	}

	public void setServletListeners(BigDecimal servletListeners) {
		this.servletListeners = servletListeners;
	}

	@Column(name = "MAX_SERVLET_LISTENERS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getMaxServletListeners() {
		return this.maxServletListeners;
	}

	public void setMaxServletListeners(BigDecimal maxServletListeners) {
		this.maxServletListeners = maxServletListeners;
	}

	@Column(name = "USER_TIMEOUT", nullable = false, precision = 38, scale = 0)
	public BigDecimal getUserTimeout() {
		return this.userTimeout;
	}

	public void setUserTimeout(BigDecimal userTimeout) {
		this.userTimeout = userTimeout;
	}

	@Column(name = "DEFAULT_HOMEPAGE", nullable = false, length = 50)
	public String getDefaultHomepage() {
		return this.defaultHomepage;
	}

	public void setDefaultHomepage(String defaultHomepage) {
		this.defaultHomepage = defaultHomepage;
	}

	@Column(name = "DEFAULT_LOGINPAGE", nullable = false, length = 50)
	public String getDefaultLoginpage() {
		return this.defaultLoginpage;
	}

	public void setDefaultLoginpage(String defaultLoginpage) {
		this.defaultLoginpage = defaultLoginpage;
	}

	@Column(name = "DEFAULT_PAGE404", nullable = false, length = 50)
	public String getDefaultPage404() {
		return this.defaultPage404;
	}

	public void setDefaultPage404(String defaultPage404) {
		this.defaultPage404 = defaultPage404;
	}

	@Column(name = "LAST_ARCHIVE_RUN", nullable = false, length = 20)
	public String getLastArchiveRun() {
		return this.lastArchiveRun;
	}

	public void setLastArchiveRun(String lastArchiveRun) {
		this.lastArchiveRun = lastArchiveRun;
	}

	@Column(name = "APPLICATION_TITLE", nullable = false, length = 1000)
	public String getApplicationTitle() {
		return this.applicationTitle;
	}

	public void setApplicationTitle(String applicationTitle) {
		this.applicationTitle = applicationTitle;
	}

	@Column(name = "RETAIN_LOGS_FOR", nullable = false, precision = 38, scale = 0)
	public BigDecimal getRetainLogsFor() {
		return this.retainLogsFor;
	}

	public void setRetainLogsFor(BigDecimal retainLogsFor) {
		this.retainLogsFor = retainLogsFor;
	}

	@Column(name = "MIN_BINARY_SIZE", precision = 38, scale = 0)
	public BigDecimal getMinBinarySize() {
		return this.minBinarySize;
	}

	public void setMinBinarySize(BigDecimal minBinarySize) {
		this.minBinarySize = minBinarySize;
	}

	@Column(name = "HTTP_PUT_IPS", nullable = false, length = 1000)
	public String getHttpPutIps() {
		return this.httpPutIps;
	}

	public void setHttpPutIps(String httpPutIps) {
		this.httpPutIps = httpPutIps;
	}

	@Column(name = "CLARK_PUBLISHER", nullable = false, length = 1000)
	public String getClarkPublisher() {
		return this.clarkPublisher;
	}

	public void setClarkPublisher(String clarkPublisher) {
		this.clarkPublisher = clarkPublisher;
	}

	@Column(name = "RETAIN_FULL_BROADCAST", precision = 38, scale = 0)
	public BigDecimal getRetainFullBroadcast() {
		return this.retainFullBroadcast;
	}

	public void setRetainFullBroadcast(BigDecimal retainFullBroadcast) {
		this.retainFullBroadcast = retainFullBroadcast;
	}

	@Column(name = "ZERO_RESULTS_PAGE", length = 50)
	public String getZeroResultsPage() {
		return this.zeroResultsPage;
	}

	public void setZeroResultsPage(String zeroResultsPage) {
		this.zeroResultsPage = zeroResultsPage;
	}

	@Column(name = "CURRENTPERIOD", precision = 38, scale = 0)
	public BigDecimal getCurrentperiod() {
		return this.currentperiod;
	}

	public void setCurrentperiod(BigDecimal currentperiod) {
		this.currentperiod = currentperiod;
	}

	@Column(name = "BRIEFINGROOMPERIOD", precision = 38, scale = 0)
	public BigDecimal getBriefingroomperiod() {
		return this.briefingroomperiod;
	}

	public void setBriefingroomperiod(BigDecimal briefingroomperiod) {
		this.briefingroomperiod = briefingroomperiod;
	}

	@Column(name = "TRUNC_COMMENTARY", precision = 38, scale = 0)
	public BigDecimal getTruncCommentary() {
		return this.truncCommentary;
	}

	public void setTruncCommentary(BigDecimal truncCommentary) {
		this.truncCommentary = truncCommentary;
	}

	@Column(name = "WAP", precision = 1, scale = 0)
	public Boolean getWap() {
		return this.wap;
	}

	public void setWap(Boolean wap) {
		this.wap = wap;
	}

	@Column(name = "ALERTS", precision = 1, scale = 0)
	public Boolean getAlerts() {
		return this.alerts;
	}

	public void setAlerts(Boolean alerts) {
		this.alerts = alerts;
	}

	@Column(name = "REPORTS", precision = 1, scale = 0)
	public Boolean getReports() {
		return this.reports;
	}

	public void setReports(Boolean reports) {
		this.reports = reports;
	}

	@Column(name = "CAMPAIGNS", precision = 1, scale = 0)
	public Boolean getCampaigns() {
		return this.campaigns;
	}

	public void setCampaigns(Boolean campaigns) {
		this.campaigns = campaigns;
	}

	@Column(name = "TOPSTORIES_EMAIL", length = 100)
	public String getTopstoriesEmail() {
		return this.topstoriesEmail;
	}

	public void setTopstoriesEmail(String topstoriesEmail) {
		this.topstoriesEmail = topstoriesEmail;
	}

	@Column(name = "COMMENTARY_TIMEOUT_WEEKDAY", precision = 63, scale = 0)
	public Double getCommentaryTimeoutWeekday() {
		return this.commentaryTimeoutWeekday;
	}

	public void setCommentaryTimeoutWeekday(Double commentaryTimeoutWeekday) {
		this.commentaryTimeoutWeekday = commentaryTimeoutWeekday;
	}

	@Column(name = "COMMENTARY_TIMEOUT_WEEKEND", precision = 63, scale = 0)
	public Double getCommentaryTimeoutWeekend() {
		return this.commentaryTimeoutWeekend;
	}

	public void setCommentaryTimeoutWeekend(Double commentaryTimeoutWeekend) {
		this.commentaryTimeoutWeekend = commentaryTimeoutWeekend;
	}

	@Column(name = "QUICK_LINK_URLS", precision = 38, scale = 0)
	public BigDecimal getQuickLinkUrls() {
		return this.quickLinkUrls;
	}

	public void setQuickLinkUrls(BigDecimal quickLinkUrls) {
		this.quickLinkUrls = quickLinkUrls;
	}

	@Column(name = "RSS_ALERTS", precision = 1, scale = 0)
	public Boolean getRssAlerts() {
		return this.rssAlerts;
	}

	public void setRssAlerts(Boolean rssAlerts) {
		this.rssAlerts = rssAlerts;
	}

	@Column(name = "RETAIN_IMAGES", precision = 38, scale = 0)
	public BigDecimal getRetainImages() {
		return this.retainImages;
	}

	public void setRetainImages(BigDecimal retainImages) {
		this.retainImages = retainImages;
	}

	@Column(name = "RETAIN_SOCIAL_MEDIA", precision = 38, scale = 0)
	public BigDecimal getRetainSocialMedia() {
		return this.retainSocialMedia;
	}

	public void setRetainSocialMedia(BigDecimal retainSocialMedia) {
		this.retainSocialMedia = retainSocialMedia;
	}

	@Column(name = "ITEMS_PER_PAGE", precision = 38, scale = 0)
	public BigDecimal getItemsPerPage() {
		return this.itemsPerPage;
	}

	public void setItemsPerPage(BigDecimal itemsPerPage) {
		this.itemsPerPage = itemsPerPage;
	}

	@Column(name = "DECAYFORSOCIALMEDIA", length = 40)
	public String getDecayforsocialmedia() {
		return this.decayforsocialmedia;
	}

	public void setDecayforsocialmedia(String decayforsocialmedia) {
		this.decayforsocialmedia = decayforsocialmedia;
	}

	@Column(name = "DAYSFORBUZZ", precision = 38, scale = 0)
	public BigDecimal getDaysforbuzz() {
		return this.daysforbuzz;
	}

	public void setDaysforbuzz(BigDecimal daysforbuzz) {
		this.daysforbuzz = daysforbuzz;
	}

	@Column(name = "BUZZ10", precision = 63, scale = 0)
	public Double getBuzz10() {
		return this.buzz10;
	}

	public void setBuzz10(Double buzz10) {
		this.buzz10 = buzz10;
	}

	@Column(name = "EOD_EMAIL_LIST", length = 100)
	public String getEodEmailList() {
		return this.eodEmailList;
	}

	public void setEodEmailList(String eodEmailList) {
		this.eodEmailList = eodEmailList;
	}

	@Column(name = "EOD_EXPIRE_AFTER", precision = 38, scale = 0)
	public BigDecimal getEodExpireAfter() {
		return this.eodExpireAfter;
	}

	public void setEodExpireAfter(BigDecimal eodExpireAfter) {
		this.eodExpireAfter = eodExpireAfter;
	}

	@Column(name = "EOD_ON", precision = 1, scale = 0)
	public Boolean getEodOn() {
		return this.eodOn;
	}

	public void setEodOn(Boolean eodOn) {
		this.eodOn = eodOn;
	}

	@Column(name = "SMA_EMAIL_LIST", length = 100)
	public String getSmaEmailList() {
		return this.smaEmailList;
	}

	public void setSmaEmailList(String smaEmailList) {
		this.smaEmailList = smaEmailList;
	}

	@Column(name = "RELOAD_PARTS", length = 2000)
	public String getReloadParts() {
		return this.reloadParts;
	}

	public void setReloadParts(String reloadParts) {
		this.reloadParts = reloadParts;
	}

	@Column(name = "TRANSCRIPT_EMAIL", length = 100)
	public String getTranscriptEmail() {
		return this.transcriptEmail;
	}

	public void setTranscriptEmail(String transcriptEmail) {
		this.transcriptEmail = transcriptEmail;
	}

	@Column(name = "PRODUCT_EMAIL", length = 100)
	public String getProductEmail() {
		return this.productEmail;
	}

	public void setProductEmail(String productEmail) {
		this.productEmail = productEmail;
	}

	@Column(name = "SHOW_EMOJI", precision = 1, scale = 0)
	public Boolean getShowEmoji() {
		return this.showEmoji;
	}

	public void setShowEmoji(Boolean showEmoji) {
		this.showEmoji = showEmoji;
	}

	@Column(name = "AZURE", precision = 1, scale = 0)
	public Boolean getAzure() {
		return this.azure;
	}

	public void setAzure(Boolean azure) {
		this.azure = azure;
	}
	
	/**
	 * Retrieves the EventsDao object corresponding to the key stored in the rsn parameter.
	 *  
	 * @param rsn The key of the record to read.
	 * @param session The current Hibernate persistence context
	 * @return The EventsDao object corresponding to the key stored in the rsn parameter.
	 */
	public static List<PreferencesDao> getPreferencesByRsn(BigDecimal rsn, Session session) {
		
		Query<PreferencesDao> query = session.createNamedQuery("Preferences_GetPreferencesByRsn", PreferencesDao.class);
		query.setParameter("rsn", rsn);
		
        List<PreferencesDao> results = query.getResultList();
        
		return results;
	}
}
