package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ReportStories generated by hbm2java
 */
@Entity
@Table(name = "REPORT_STORIES", schema = "TNO")
public class ReportStoriesDao implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal rsn;
	private BigDecimal reportRsn;
	private String headline;
	private BigDecimal reportSectionRsn;
	private BigDecimal sortPosition;
	private BigDecimal tocPosition;
	private String summary;
	private Clob content;
	private BigDecimal itemRsn;
	private BigDecimal dateTime;
	private BigDecimal sourceTypeRsn;

	public ReportStoriesDao() {
	}

	public ReportStoriesDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public ReportStoriesDao(BigDecimal rsn, BigDecimal reportRsn, String headline, BigDecimal reportSectionRsn,
			BigDecimal sortPosition, BigDecimal tocPosition, String summary, Clob content, BigDecimal itemRsn,
			BigDecimal dateTime, BigDecimal sourceTypeRsn) {
		this.rsn = rsn;
		this.reportRsn = reportRsn;
		this.headline = headline;
		this.reportSectionRsn = reportSectionRsn;
		this.sortPosition = sortPosition;
		this.tocPosition = tocPosition;
		this.summary = summary;
		this.content = content;
		this.itemRsn = itemRsn;
		this.dateTime = dateTime;
		this.sourceTypeRsn = sourceTypeRsn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "next_rsn")
	@SequenceGenerator(name = "next_rsn", sequenceName = "NEXT_RSN", allocationSize=1)
	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "REPORT_RSN", precision = 38, scale = 0)
	public BigDecimal getReportRsn() {
		return this.reportRsn;
	}

	public void setReportRsn(BigDecimal reportRsn) {
		this.reportRsn = reportRsn;
	}

	@Column(name = "HEADLINE", length = 1000)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "REPORT_SECTION_RSN", precision = 38, scale = 0)
	public BigDecimal getReportSectionRsn() {
		return this.reportSectionRsn;
	}

	public void setReportSectionRsn(BigDecimal reportSectionRsn) {
		this.reportSectionRsn = reportSectionRsn;
	}

	@Column(name = "SORT_POSITION", precision = 38, scale = 0)
	public BigDecimal getSortPosition() {
		return this.sortPosition;
	}

	public void setSortPosition(BigDecimal sortPosition) {
		this.sortPosition = sortPosition;
	}

	@Column(name = "TOC_POSITION", precision = 38, scale = 0)
	public BigDecimal getTocPosition() {
		return this.tocPosition;
	}

	public void setTocPosition(BigDecimal tocPosition) {
		this.tocPosition = tocPosition;
	}

	@Column(name = "SUMMARY", length = 2000)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "CONTENT")
	public Clob getContent() {
		return this.content;
	}

	public void setContent(Clob content) {
		this.content = content;
	}

	@Column(name = "ITEM_RSN", precision = 38, scale = 0)
	public BigDecimal getItemRsn() {
		return this.itemRsn;
	}

	public void setItemRsn(BigDecimal itemRsn) {
		this.itemRsn = itemRsn;
	}

	@Column(name = "DATE_TIME", precision = 38, scale = 0)
	public BigDecimal getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(BigDecimal dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "SOURCE_TYPE_RSN", precision = 38, scale = 0)
	public BigDecimal getSourceTypeRsn() {
		return this.sourceTypeRsn;
	}

	public void setSourceTypeRsn(BigDecimal sourceTypeRsn) {
		this.sourceTypeRsn = sourceTypeRsn;
	}

}
