package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReportForBlackberry generated by hbm2java
 */
@Entity
@Table(name = "REPORT_FOR_BLACKBERRY", schema = "TNO")
public class ReportForBlackberryDao implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal rsn;
	private BigDecimal reportRsn;
	private Date dateCreated;
	private Date dateLastViewed;
	private Clob content;

	public ReportForBlackberryDao() {
	}

	public ReportForBlackberryDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public ReportForBlackberryDao(BigDecimal rsn, BigDecimal reportRsn, Date dateCreated, Date dateLastViewed,
			Clob content) {
		this.rsn = rsn;
		this.reportRsn = reportRsn;
		this.dateCreated = dateCreated;
		this.dateLastViewed = dateLastViewed;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "next_rsn")
	@SequenceGenerator(name = "next_rsn", sequenceName = "NEXT_RSN", allocationSize=1)
	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "REPORT_RSN", precision = 38, scale = 0)
	public BigDecimal getReportRsn() {
		return this.reportRsn;
	}

	public void setReportRsn(BigDecimal reportRsn) {
		this.reportRsn = reportRsn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATED", length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_LAST_VIEWED", length = 7)
	public Date getDateLastViewed() {
		return this.dateLastViewed;
	}

	public void setDateLastViewed(Date dateLastViewed) {
		this.dateLastViewed = dateLastViewed;
	}

	@Column(name = "CONTENT")
	public Clob getContent() {
		return this.content;
	}

	public void setContent(Clob content) {
		this.content = content;
	}

}
