package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * SavedEmailAlerts generated by hbm2java
 */
@Entity
@Table(name = "SAVED_EMAIL_ALERTS", schema = "TNO")
public class SavedEmailAlertsDao implements java.io.Serializable {

	private BigDecimal rsn;
	private String alertrsn;
	private String username;
	private String recipients;
	private String subject;
	private Clob message;
	private String bcc;
	private String alertrsns;

	public SavedEmailAlertsDao() {
	}

	public SavedEmailAlertsDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public SavedEmailAlertsDao(BigDecimal rsn, String alertrsn, String username, String recipients, String subject,
			Clob message, String bcc, String alertrsns) {
		this.rsn = rsn;
		this.alertrsn = alertrsn;
		this.username = username;
		this.recipients = recipients;
		this.subject = subject;
		this.message = message;
		this.bcc = bcc;
		this.alertrsns = alertrsns;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "next_rsn")
	@SequenceGenerator(name = "next_rsn", sequenceName = "NEXT_RSN", allocationSize=1)
	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "ALERTRSN", length = 20)
	public String getAlertrsn() {
		return this.alertrsn;
	}

	public void setAlertrsn(String alertrsn) {
		this.alertrsn = alertrsn;
	}

	@Column(name = "USERNAME", length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "RECIPIENTS", length = 500)
	public String getRecipients() {
		return this.recipients;
	}

	public void setRecipients(String recipients) {
		this.recipients = recipients;
	}

	@Column(name = "SUBJECT", length = 500)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "MESSAGE")
	public Clob getMessage() {
		return this.message;
	}

	public void setMessage(Clob message) {
		this.message = message;
	}

	@Column(name = "BCC", length = 4000)
	public String getBcc() {
		return this.bcc;
	}

	public void setBcc(String bcc) {
		this.bcc = bcc;
	}

	@Column(name = "ALERTRSNS", length = 4000)
	public String getAlertrsns() {
		return this.alertrsns;
	}

	public void setAlertrsns(String alertrsns) {
		this.alertrsns = alertrsns;
	}
	
	/**
	 * Get all records in the SAVED_EMAIL_ALERTS table. 
	 * 
	 * @param session The current Hibernate persistence context
	 * @return A list containing all records in the SAVED_EMAIL_ALERTS table.
	 */
	public static List<SavedEmailAlertsDao> getSavedEmailAlerts(Session session) {
		
		String sqlStmt = "from SavedEmailAlertsDao";

		Query<SavedEmailAlertsDao> query = session.createQuery(sqlStmt, SavedEmailAlertsDao.class);
        List<SavedEmailAlertsDao> results = query.getResultList();
        
		return results;
	}
	
	/**
	 * Delete all records in the SAVED_EMAIL_ALERTS table. 
	 * 
	 * @param session The current Hibernate persistence context
	 * @return A list containing all records in the SAVED_EMAIL_ALERTS table.
	 */
	public static void deleteSavedEmailAlerts(String rsnList, Session session) {
		
		String sqlStmt = "delete from SavedEmailAlertsDao where rsn in (" + rsnList + ")";

		Query<SavedEmailAlertsDao> query = session.createQuery(sqlStmt);
		session.beginTransaction();
        query.executeUpdate();
        session.getTransaction().commit();
	}
}
