package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.Session;
import org.hibernate.query.Query;

/**
 * SourceTypes generated by hbm2java
 */
@Entity
@Table(name = "SOURCE_TYPES", schema = "TNO")
public class SourceTypesDao implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal rsn;
	private String type;
	private String clarktype;
	private BigDecimal sortOrder;
	private Boolean expirationFlag;
	private BigDecimal days;
	private BigDecimal action;
	private String partName;
	private BigDecimal special;
	private String detailPage;
	private String detailPageFormat;
	private BigDecimal truncHeadline;
	private String wapLineFormat;
	private String wapPageFormat;
	private String tab;
	private Boolean useHeader;
	private Boolean useInAnalysis;

	public SourceTypesDao() {
	}

	public SourceTypesDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public SourceTypesDao(BigDecimal rsn, String type, String clarktype, BigDecimal sortOrder, Boolean expirationFlag,
			BigDecimal days, BigDecimal action, String partName, BigDecimal special, String detailPage,
			String detailPageFormat, BigDecimal truncHeadline, String wapLineFormat, String wapPageFormat, String tab,
			Boolean useHeader, Boolean useInAnalysis) {
		this.rsn = rsn;
		this.type = type;
		this.clarktype = clarktype;
		this.sortOrder = sortOrder;
		this.expirationFlag = expirationFlag;
		this.days = days;
		this.action = action;
		this.partName = partName;
		this.special = special;
		this.detailPage = detailPage;
		this.detailPageFormat = detailPageFormat;
		this.truncHeadline = truncHeadline;
		this.wapLineFormat = wapLineFormat;
		this.wapPageFormat = wapPageFormat;
		this.tab = tab;
		this.useHeader = useHeader;
		this.useInAnalysis = useInAnalysis;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "TYPE", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "CLARKTYPE", length = 30)
	public String getClarktype() {
		return this.clarktype;
	}

	public void setClarktype(String clarktype) {
		this.clarktype = clarktype;
	}

	@Column(name = "SORT_ORDER", precision = 38, scale = 0)
	public BigDecimal getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(BigDecimal sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "EXPIRATION_FLAG", precision = 1, scale = 0)
	public Boolean getExpirationFlag() {
		return this.expirationFlag;
	}

	public void setExpirationFlag(Boolean expirationFlag) {
		this.expirationFlag = expirationFlag;
	}

	@Column(name = "DAYS", precision = 38, scale = 0)
	public BigDecimal getDays() {
		return this.days;
	}

	public void setDays(BigDecimal days) {
		this.days = days;
	}

	@Column(name = "ACTION", precision = 38, scale = 0)
	public BigDecimal getAction() {
		return this.action;
	}

	public void setAction(BigDecimal action) {
		this.action = action;
	}

	@Column(name = "PART_NAME", length = 50)
	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	@Column(name = "SPECIAL", precision = 38, scale = 0)
	public BigDecimal getSpecial() {
		return this.special;
	}

	public void setSpecial(BigDecimal special) {
		this.special = special;
	}

	@Column(name = "DETAIL_PAGE", length = 50)
	public String getDetailPage() {
		return this.detailPage;
	}

	public void setDetailPage(String detailPage) {
		this.detailPage = detailPage;
	}

	@Column(name = "DETAIL_PAGE_FORMAT", length = 50)
	public String getDetailPageFormat() {
		return this.detailPageFormat;
	}

	public void setDetailPageFormat(String detailPageFormat) {
		this.detailPageFormat = detailPageFormat;
	}

	@Column(name = "TRUNC_HEADLINE", precision = 38, scale = 0)
	public BigDecimal getTruncHeadline() {
		return this.truncHeadline;
	}

	public void setTruncHeadline(BigDecimal truncHeadline) {
		this.truncHeadline = truncHeadline;
	}

	@Column(name = "WAP_LINE_FORMAT", length = 50)
	public String getWapLineFormat() {
		return this.wapLineFormat;
	}

	public void setWapLineFormat(String wapLineFormat) {
		this.wapLineFormat = wapLineFormat;
	}

	@Column(name = "WAP_PAGE_FORMAT", length = 50)
	public String getWapPageFormat() {
		return this.wapPageFormat;
	}

	public void setWapPageFormat(String wapPageFormat) {
		this.wapPageFormat = wapPageFormat;
	}

	@Column(name = "TAB", length = 50)
	public String getTab() {
		return this.tab;
	}

	public void setTab(String tab) {
		this.tab = tab;
	}

	@Column(name = "USE_HEADER", precision = 1, scale = 0)
	public Boolean getUseHeader() {
		return this.useHeader;
	}

	public void setUseHeader(Boolean useHeader) {
		this.useHeader = useHeader;
	}

	@Column(name = "USE_IN_ANALYSIS", precision = 1, scale = 0)
	public Boolean getUseInAnalysis() {
		return this.useInAnalysis;
	}

	public void setUseInAnalysis(Boolean useInAnalysis) {
		this.useInAnalysis = useInAnalysis;
	}
	
	/**
	 * Get a list of expiring sourceTypes.
	 * 
	 * @param session The current Hibernate persistence context
	 * @return A list of SourceTypesDao records for sources that expire.
	 */
	public static List<SourceTypesDao> getExpiringSourceTypes(Session session) {
		
		String sqlStmt = "from SourceTypesDao where expirationFlag = 1 and action = 2";

		Query<SourceTypesDao> query = session.createQuery(sqlStmt, SourceTypesDao.class);
        List<SourceTypesDao> results = query.getResultList();
        
		return results;
	}

}
