package ca.bc.gov.tno.jorel2.model;
// Generated Dec 24, 2019, 8:06:31 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.Session;
import org.hibernate.query.Query;

import ca.bc.gov.tno.jorel2.Jorel2Instance;
import ca.bc.gov.tno.jorel2.util.DateUtil;

/**
 * SourcePaperImages generated by hbm2java
 */
@Entity
@Table(name = "SOURCE_PAPER_IMAGES", schema = "TNO")
public class SourcePaperImagesDao implements java.io.Serializable {

	private BigDecimal rsn;
	private BigDecimal sourceRsn;
	private Date paperDate;
	private BigDecimal width;
	private BigDecimal height;
	private String binaryPath;
	private String fileName;

	public SourcePaperImagesDao() {
	}

	public SourcePaperImagesDao(BigDecimal rsn) {
		this.rsn = rsn;
	}

	public SourcePaperImagesDao(BigDecimal rsn, BigDecimal sourceRsn, Date paperDate, BigDecimal width, BigDecimal height,
			String binaryPath, String fileName) {
		this.rsn = rsn;
		this.sourceRsn = sourceRsn;
		this.paperDate = paperDate;
		this.width = width;
		this.height = height;
		this.binaryPath = binaryPath;
		this.fileName = fileName;
	}

	@Id

	@Column(name = "RSN", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getRsn() {
		return this.rsn;
	}

	public void setRsn(BigDecimal rsn) {
		this.rsn = rsn;
	}

	@Column(name = "SOURCE_RSN", precision = 38, scale = 0)
	public BigDecimal getSourceRsn() {
		return this.sourceRsn;
	}

	public void setSourceRsn(BigDecimal sourceRsn) {
		this.sourceRsn = sourceRsn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAPER_DATE", length = 7)
	public Date getPaperDate() {
		return this.paperDate;
	}

	public void setPaperDate(Date paperDate) {
		this.paperDate = paperDate;
	}

	@Column(name = "WIDTH", precision = 38, scale = 0)
	public BigDecimal getWidth() {
		return this.width;
	}

	public void setWidth(BigDecimal width) {
		this.width = width;
	}

	@Column(name = "HEIGHT", precision = 38, scale = 0)
	public BigDecimal getHeight() {
		return this.height;
	}

	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	@Column(name = "BINARY_PATH", length = 1000)
	public String getBinaryPath() {
		return this.binaryPath;
	}

	public void setBinaryPath(String binaryPath) {
		this.binaryPath = binaryPath;
	}

	@Column(name = "FILE_NAME", length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	
	/**
	 * Deletes old versions of source paper images.
	 * 
	 * @param rsn The source rsn for this import.
	 * @param localDate The date the paper containing this image was published.
	 * @param session - The currently active Hibernate DB session
	 */
	
	public static void deleteByRsnAndDate(BigDecimal rsn, LocalDate localDate, Session session) {

		Date utilDate = DateUtil.dateFromLocalDate(localDate);
	    String qryString = "delete from SourcePaperImagesDao s where s.sourceRsn = :sourceRsn and s.paperDate = :date";
	    Query<?> query = session.createQuery(qryString);
		query.setParameter("sourceRsn", rsn);
		query.setParameter("date", utilDate);
		
		session.beginTransaction();
	    int count = query.executeUpdate();
		session.getTransaction().commit();
	}
}
